import { LivingWorld } from './globe.js';
const icons={menu:'<path d="M3 5h14M3 10h8M3 15h11"/>',down:'<path d="m5 7 5 5 5-5"/>',seed:'<path d="M10 18v-8M10 12C2 12 2 7 2 5c6 0 8 3 8 7ZM10 8c0-5 4-6 8-6 0 5-2 8-8 8"/>',tree:'<path d="M10 18v-6m0 3-4-3m4 1 3-3M7 3a4 4 0 0 1 7 2 4 4 0 0 1 2 7H5A4 4 0 0 1 4 5a3 3 0 0 1 3-2Z"/>',footprints:'<ellipse cx="6" cy="6" rx="2.5" ry="4" transform="rotate(-20 6 6)"/><ellipse cx="14" cy="11" rx="2.5" ry="4" transform="rotate(20 14 11)"/><path d="m5 13 1 2m8 3 1-1"/>',leaf:'<path d="M4 16C-1 4 9 2 17 2c1 10-4 16-12 13M3 18 13 7"/>',world:'<circle cx="10" cy="10" r="8"/><ellipse cx="10" cy="10" rx="3.5" ry="8"/><path d="M2 10h16"/>',compass:'<circle cx="10" cy="10" r="8"/><path d="m13.5 6.5-2 5-5 2 2-5 5-2Z"/>',plus:'<path d="M10 4v12M4 10h12"/>',minus:'<path d="M4 10h12"/>',rotate:'<path d="M3 8a7 7 0 1 1 1 7M3 3v5h5"/>',locate:'<path d="m3 3 14 5-7 3-3 7-4-15Z"/>',chat:'<path d="M3 3h14v10H8l-5 4V3Z"/>',close:'<path d="m5 5 10 10M15 5 5 15"/>',check:'<path d="m4 10 4 4 8-9"/>',camera:'<path d="M2 6h4l1-3h6l1 3h4v11H2Z"/><circle cx="10" cy="11" r="3"/>',book:'<path d="M10 5C7 3 4 3 2 4v12c3-1 5-1 8 1 3-2 5-2 8-1V4c-3-1-5-1-8 1v12"/>',settings:'<path d="M3 5h14M3 10h14M3 15h14"/><circle cx="7" cy="5" r="2"/><circle cx="13" cy="10" r="2"/><circle cx="6" cy="15" r="2"/>',sun:'<circle cx="10" cy="10" r="4"/><path d="M10 1v2m0 14v2M1 10h2m14 0h2M3 3l2 2m10 10 2 2M3 17l2-2M15 5l2-2"/>',flower:'<circle cx="10" cy="9" r="2"/><path d="M8 6C2 0 0 7 6 9c-7 2-3 9 2 4 1 6 7 5 5-1 7 1 7-6 1-5 3-6-3-8-4-3M10 14v5"/>',arrow:'<path d="M4 10h12m-5-5 5 5-5 5"/>',bird:'<path d="M2 10c4-3 6-3 8 1 2-4 5-4 8-1"/>',heart:'<path d="M10 17 3 10C-1 3 7 0 10 5c3-5 11-2 7 5Z"/>',download:'<path d="M10 2v11m-4-4 4 4 4-4M3 14v4h14v-4"/>'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<svg viewBox="0 0 20 20" aria-hidden="true">${icons[n]||icons.leaf}</svg>`;
function hydrate(){$$('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));}
let state={walks:[],observations:[],owned:[],spent:0,name:'',companion:'Lumi',light:'day',reduced:false};
try{const s=JSON.parse(localStorage.getItem('seqesta-nature-v2')||'{}');state={...state,...s};}catch{}
for(const key of ['walks','observations','owned'])if(!Array.isArray(state[key]))state[key]=[];
let world,toastTimer,walk=null,watchId=null,ticker=null,lastFix=null,sessionDistance=0,closeFocus=null,breathTimer=null;
let sheetName='';let chats=[];
const fmt=n=>Math.round(n).toLocaleString('en-GB');
const todayKey=()=>new Date().toLocaleDateString('en-CA');
const sameDay=d=>new Date(d).toLocaleDateString('en-CA')===todayKey();
const totalSteps=()=>state.walks.reduce((n,w)=>n+w.steps,0);
const totalSeeds=()=>state.walks.reduce((n,w)=>n+w.seeds,0);
const balance=()=>Math.max(0,totalSeeds()-state.spent);
function persist(){try{localStorage.setItem('seqesta-nature-v2',JSON.stringify(state));return true;}catch{toast('Device storage is full. Download your field notes to keep a copy.');return false;}}
function toast(t){clearTimeout(toastTimer);$('#toast').textContent=t;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3600);}
function refresh(){
 const todays=state.walks.filter(w=>sameDay(w.date)),steps=todays.reduce((n,w)=>n+w.steps,0);
 $('#today-steps').textContent=fmt(steps);$('#seed-count').textContent=fmt(balance());
 $('#step-fill').style.width=Math.min(steps/6000*100,100)+'%';$('#step-progress').setAttribute('aria-valuenow',Math.min(steps,6000));
 $('#today-distance').textContent=todays.reduce((n,w)=>n+w.distance,0).toFixed(1)+' km';$('#today-seeds').textContent=todays.reduce((n,w)=>n+w.seeds,0)+' seeds grown';
 $('#progress-message').textContent=steps===0?'Every step is a place to start.':steps>=6000?'A little greener, thanks to you.':`${fmt(6000-steps)} steps to your daily trail.`;
 const level=Math.floor(totalSteps()/3000)+1;$('#tree-level').textContent=`Level ${level} · ${level<3?'Taking root':level<6?'Branching out':'Growing wild'}`;
 world?.grow(totalSteps());world?.decorate(state.owned);world?.setLight(state.light);if(world)world.reduced=state.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches;
 document.body.classList.toggle('reduce-motion',state.reduced);$('.companion-button span').textContent='Say hello to '+state.companion;
}
function openSheet(title,content,name=''){if(breathTimer){clearInterval(breathTimer);breathTimer=null;}sheetName=name;closeFocus=document.activeElement;$('#sheet-content').innerHTML=`<div class="sheet-inner"><header class="sheet-header"><span class="eyebrow">${title}</span><button class="close-button" data-action="close" aria-label="Close panel">${icon('close')}</button></header>${content}</div>`;if(!$('#sheet').open)$('#sheet').showModal();hydrate();$('#sheet').scrollTop=0;}
function closeSheet(){if(breathTimer){clearInterval(breathTimer);breathTimer=null;}$('#sheet').close();closeFocus?.focus?.();$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.action==='home'));}
function showWalk(){openSheet('STEP OUTSIDE',`<h2>A little walk.<br>A little more world.</h2><p>Every 100 steps earns a virtual seed. Every walk helps your digital tree grow.</p><button class="option-card" data-action="start-gps"><span class="option-icon">${icon('locate')}</span><span><h3>Start a walk</h3><p>Track time and distance with your location.</p></span><span class="arrow">↗</span></button><button class="option-card" data-action="log-walk"><span class="option-icon">${icon('footprints')}</span><span><h3>Already been outside?</h3><p>Log a walk using your step count.</p></span><span class="arrow">↗</span></button><p class="fine-print">Location is optional and used only while tracking. Distance-based steps are estimates. This preview does not connect to your phone’s health data or track walks in the background.</p>`,'walk');}
function showLog(){openSheet('A WALK, WELL SPENT',`<h2>Bring your walk<br>back to your world.</h2><p>Add the steps from your phone or watch. Your tree will take it from here.</p><form id="log-walk-form"><label class="field-label" for="walk-name">Name your walk <span>(optional)</span></label><input class="field" id="walk-name" name="title" placeholder="The long way home" maxlength="70"><div class="field-pair"><div><label class="field-label" for="walk-steps">Steps</label><input class="field" id="walk-steps" name="steps" type="number" min="1" max="100000" step="1" placeholder="1,500" required></div><div><label class="field-label" for="walk-minutes">Minutes</label><input class="field" id="walk-minutes" name="minutes" type="number" min="1" max="1440" step="1" placeholder="15" required></div></div><label class="field-label" for="walk-date">Walk date</label><input class="field" id="walk-date" name="date" type="date" value="${localISO()}" max="${localISO()}" required><div class="action-row"><button class="primary" type="submit">Let it grow ${icon('seed')}</button></div></form><p class="fine-print">Manually logged steps. Seeds are in-app rewards with no cash value. Distance is estimated using 0.75 metres per step.</p>`,'log');}
function localISO(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function saveWalk({steps,minutes,date,title,source,distance}){
 if(!Number.isFinite(steps)||steps<1||steps>100000||!Number.isFinite(minutes)||minutes<0||minutes>1440)throw new Error('Add a valid step count and duration.');
 const entry={id:crypto.randomUUID(),steps:Math.round(steps),minutes:Math.round(minutes*10)/10,date:date||new Date().toISOString(),title:title||'A little outside',source,distance:distance??steps*.00075,seeds:Math.floor((totalSteps()+Math.round(steps))/100)-Math.floor(totalSteps()/100)};
 state.walks.push(entry);if(!persist()){state.walks.pop();throw new Error('Your walk could not be saved. Free some device storage and try again.');}refresh();return entry;
}
function showWalkSuccess(entry){openSheet('YOUR WORLD GREW A LITTLE',`<div class="success-mark">${icon('seed')}</div><h2 class="center">A good day<br>to take root.</h2><p class="center">${esc(entry.title)} is now part of your world.</p><div class="stat-grid"><div class="stat-tile"><strong>${fmt(entry.steps)}</strong><span>${entry.source==='gps'?'estimated steps':'steps logged'}</span></div><div class="stat-tile"><strong>+${entry.seeds}</strong><span>virtual seeds earned</span></div></div><button class="primary full" data-action="view-tree">See what’s growing ${icon('tree')}</button><button class="secondary full" data-action="observation" style="margin-top:10px">Did you notice something? Add a field note</button><p class="fine-print">${entry.source==='gps'?'Distance tracked during this visit; steps estimated from distance.':'Self-reported walk; distance estimated from steps.'} Your progress is saved on this device.</p>`,'walk-success');}
function showTree(){const steps=totalSteps(),level=Math.floor(steps/3000)+1,toNext=3000-steps%3000;openSheet('YOUR DIGITAL TREE',`<h2>A living reminder<br>of getting outside.</h2><p>Every walk becomes a little more growth. This tree is your digital companion to real-world activity.</p><div class="progress-block"><div class="tree-big">${icon('tree')}</div><h3>Level ${level} · ${level<3?'Taking root':level<6?'Branching out':'Growing wild'}</h3><p>${fmt(toNext)} steps to your next level</p><div class="progress-track"><span style="width:${steps%3000/30}%"></span></div></div><div class="milestone-list">${[[0,'A place to begin','Your world is here.'],[3000,'Finding your feet','Your tree grows a little taller.'],[9000,'Branching out','A canopy of little adventures.'],[18000,'Growing wild','Your everyday is taking root.']].map(([n,t,d])=>`<div class="milestone ${steps>=n?'completed':''}"><span class="milestone-circle">${steps>=n?'✓':'○'}</span><span>${t}<small>${d} ${n?fmt(n)+' steps':''}</small></span></div>`).join('')}</div><button class="primary full" data-action="close">Back to my world</button><p class="fine-print">A digital tree, grown through your logged activity. It does not represent a tree planted in the real world.</p>`,'tree');}
function showActivity(){const dist=state.walks.reduce((s,w)=>s+w.distance,0);openSheet('YOUR LITTLE ADVENTURES',`<h2>One walk<br>becomes a habit.</h2><div class="stat-grid"><div class="stat-tile"><strong>${fmt(totalSteps())}</strong><span>steps logged</span></div><div class="stat-tile"><strong>${dist.toFixed(1)}<small style="font-size:12px"> km</small></strong><span>tracked & estimated distance</span></div></div><div class="list-title">Your walks <span>${state.walks.length} adventures</span></div>${state.walks.length?[...state.walks].reverse().map(w=>`<div class="activity-item"><span class="activity-icon">${icon('footprints')}</span><span><h3>${esc(w.title)}</h3><p>${dateLabel(w.date)} · ${w.minutes} min · ${w.source==='gps'?'distance tracked':'manually logged'}</p></span><strong>${fmt(w.steps)}<span style="display:block;font-size:8px;text-align:right;color:#9aa887;margin-top:5px">+${w.seeds} seeds</span></strong></div>`).join(''):`<div class="empty">${icon('footprints')}Your first adventure is still ahead.<br>It can be as small as the long way home.</div>`}<button class="primary full" data-action="log-walk" style="margin-top:25px">Log a walk ${icon('plus')}</button>`,'activity');}
function dateLabel(d){return new Date(d).toLocaleDateString('en-GB',{day:'numeric',month:'short'});}
// A coherent first slice: the live globe, its controls, and walking entry points.
const actions={home:()=>{closeSheet();world?.reset()},close:closeSheet,walk:()=>walk?toast('Your walk is already in progress.'):showWalk(),'log-walk':showLog,tree:showTree,activity:showActivity,'view-tree':()=>{closeSheet();world?.focus();},perspective:()=>world?.focused?world.reset():world?.focus(),'zoom-in':()=>world?.zoom(.8),'zoom-out':()=>world?.zoom(1.25),rotate:()=>world?.rotate(.4),recenter:()=>world?.reset(),reload:()=>location.reload()};
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.matches('.wordmark')){e.preventDefault();world?.reset();return;}if(b.dataset.action)actions[b.dataset.action]?.();});
document.addEventListener('submit',e=>{if(e.target.id!=='log-walk-form')return;e.preventDefault();const f=new FormData(e.target);const steps=Number(f.get('steps')),minutes=Number(f.get('minutes')),day=String(f.get('date'));if(day>localISO()){toast('Choose today or a day in the past.');return;}try{const entry=saveWalk({steps,minutes,date:new Date(day+'T12:00:00').toISOString(),title:String(f.get('title')).trim(),source:'manual'});showWalkSuccess(entry);}catch(err){toast(err.message);}});
$('#sheet').addEventListener('click',e=>{if(e.target===$('#sheet')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeSheet();}});
$('#sheet').addEventListener('close',()=>{if(breathTimer){clearInterval(breathTimer);breathTimer=null;}});
hydrate();
try{world=new LivingWorld($('#world-canvas'),{onSelect:type=>type==='tree'?showTree():actions.companion?.(),onFocus:focused=>{document.body.classList.toggle('focused',focused);$('#perspective-label').textContent=focused?'In your world':'Your little world';$('#world-hint').textContent=focused?'Pinch out to explore · Tap the arrow to return':'Drag to wander · Pinch or scroll to get closer';},onError:()=>{$('#world-fallback').hidden=false;}});}catch(error){$('#world-fallback').hidden=false;console.error('World could not start:',error);}
refresh();

// Foreground walk tracking. No background or health-store step counting is implied.
function elapsedMs(){return walk?walk.elapsed+(walk.paused?0:Date.now()-walk.segmentStarted):0;}
function distanceBetween(a,b){const rad=n=>n*Math.PI/180,dy=rad(b.latitude-a.latitude),dx=rad(b.longitude-a.longitude),v=Math.sin(dy/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dx/2)**2;return 6371*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v));}
function beginLocation(){
 if(!navigator.geolocation){if(walk)walk.message='Location is unavailable. You can add your steps when you finish.';renderWalk();return;}
 watchId=navigator.geolocation.watchPosition(pos=>{
  if(!walk||walk.paused)return;const c=pos.coords;
  if(c.accuracy>65){walk.message='Waiting for a more accurate location. Time is still being tracked.';renderWalk();return;}
  const fix={latitude:c.latitude,longitude:c.longitude,accuracy:c.accuracy,time:pos.timestamp};
  if(lastFix){const d=distanceBetween(lastFix,fix),dt=(fix.time-lastFix.time)/1000;
   if(dt>0&&d*1000/dt<4.5&&d*1000>=Math.max(5,c.accuracy*.35)){sessionDistance+=d;lastFix=fix;}
   else if(dt>45||d*1000/dt>=4.5)lastFix=fix;
  }else lastFix=fix;
  walk.message='Location active · steps are estimated from distance.';renderWalk();
 },err=>{if(!walk)return;walk.message=err.code===1?'Location wasn’t allowed. Add your steps when you finish.':'Location is unavailable right now. Time is still being tracked.';renderWalk();},{enableHighAccuracy:true,maximumAge:3000,timeout:20000});
}
function startWalk(){if(walk){closeSheet();return;}walk={elapsed:0,segmentStarted:Date.now(),paused:false,message:'Finding your location…'};sessionDistance=0;lastFix=null;closeSheet();document.body.classList.add('walking');$('#active-walk').hidden=false;if(world)world.walking=true;renderWalk();ticker=setInterval(renderWalk,1000);beginLocation();}
function stopWatch(){if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null;}lastFix=null;}
function pauseWalk(){if(!walk)return;if(!walk.paused){walk.elapsed=elapsedMs();walk.paused=true;stopWatch();if(world)world.walking=false;}else{walk.segmentStarted=Date.now();walk.paused=false;if(world)world.walking=true;beginLocation();}renderWalk();}
function renderWalk(){if(!walk)return;const seconds=Math.floor(elapsedMs()/1000),time=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;$('#active-walk').innerHTML=`<div class="active-walk-top"><span class="eyebrow">${walk.paused?'A LITTLE PAUSE':'OUT IN THE WORLD'}</span><strong class="timer">${time}</strong></div><div class="active-walk-stats"><span>${sessionDistance.toFixed(2)} km tracked</span><span>~${fmt(sessionDistance/.00075)} steps</span></div><div class="walk-controls"><button data-action="pause-walk">${walk.paused?'Resume walk':'Pause'}</button><button class="finish-button" data-action="finish-walk">Finish walk ↗</button></div><p class="active-walk-message">${esc(walk.paused?'Paused. Resume when you’re ready.':walk.message)}</p>`;}
function finishWalk(){if(!walk)return;if(!walk.paused)pauseWalk();const steps=Math.round(sessionDistance/.00075),minutes=Math.max(1,Math.round(elapsedMs()/60000));openSheet('WELCOME BACK',`<h2>Bring a little<br>outside home.</h2><p>You walked for ${minutes} ${minutes===1?'minute':'minutes'}${sessionDistance>0?` and tracked ${sessionDistance.toFixed(2)} km`:''}. Review your steps before growing your world.</p><form id="finish-walk-form"><label class="field-label" for="finish-title">Name this walk</label><input class="field" id="finish-title" name="title" placeholder="A little outside" maxlength="70"><label class="field-label" for="finish-steps">${steps>0?'Estimated steps · you can adjust this':'Add steps from your phone or watch'}</label><input class="field" id="finish-steps" name="steps" type="number" min="1" max="100000" step="1" required value="${steps||''}" placeholder="Your step count"><p class="fine-print">${steps>0?'Estimated using 0.75 metres per step.':'No walking distance was recorded. Your timer does not automatically count steps.'}</p><div class="action-row"><button class="primary" type="submit">Grow my world ${icon('seed')}</button></div></form><button class="secondary full" data-action="resume-walk" style="margin-top:11px">Keep walking</button><button data-action="discard-walk" style="font-size:10px;color:#99a386;margin-top:21px">Discard this walk</button>`,'finish-walk');}
function clearWalk(){stopWatch();clearInterval(ticker);ticker=null;walk=null;sessionDistance=0;document.body.classList.remove('walking');$('#active-walk').hidden=true;if(world)world.walking=false;}
const rewards=[{id:'daisies',title:'A scatter of daisies',description:'Little bright spots along the way. Add a scattering of flowers to your world.',cost:15,icon:'flower'},{id:'wildflowers',title:'Let the wildflowers in',description:'More colour, more little wonders. Grow a new patch of wildflowers.',cost:30,icon:'leaf'},{id:'grove',title:'A pocket of woodland',description:'A pair of young trees for your corner of the universe.',cost:50,icon:'tree'}];
function showRewards(){openSheet('LITTLE STEPS. LOVELY THINGS.',`<h2>Make your world<br>a little wilder.</h2><p>Spend the seeds from your walks on little things that make your world feel like you.</p><div class="list-title">Your seed pocket <span style="color:#69814d;font-size:13px">${fmt(balance())} seeds</span></div>${rewards.map(r=>`<article class="reward-item"><div class="reward-symbol">${icon(r.icon)}</div><h3>${r.title}</h3><p>${r.description}</p><div class="reward-bottom"><span class="reward-cost">${icon('seed')} ${r.cost} seeds</span><button data-buy="${r.id}" ${state.owned.includes(r.id)||balance()<r.cost?'disabled':''} class="${state.owned.includes(r.id)?'owned':''}">${state.owned.includes(r.id)?'Growing in your world ✓':balance()<r.cost?`${r.cost-balance()} more to go`:'Add to my world'}</button></div></article>`).join('')}<p class="fine-print">Virtual rewards only. Seeds have no cash value. Partner offers and sponsored nature contributions are not connected in this preview.</p>`,'rewards');}
function buyReward(id){const r=rewards.find(r=>r.id===id);if(!r||state.owned.includes(id)||balance()<r.cost)return;state.owned.push(id);state.spent+=r.cost;if(!persist()){state.owned.pop();state.spent-=r.cost;return;}refresh();showRewards();toast('A little more life in your world.');}
const quests=[{id:'tree',title:'Meet a neighbour with roots.',description:'Find a tree on your walk. Look at the shape of its leaves, feel its bark, and notice who else calls it home.',category:'Trees',icon:'tree',time:'5 MIN · ANYWHERE WITH A TREE'},{id:'bird',title:'Let the birds set the pace.',description:'Pause for a minute. How many different calls can you hear? You don’t need to know their names to notice them.',category:'Birds',icon:'bird',time:'2 MIN · JUST STOP AND LISTEN'},{id:'small',title:'Find the tiny, extraordinary.',description:'A leaf, a little flower, a patch of moss. Get closer to one small thing you would usually walk past.',category:'Plants',icon:'flower',time:'3 MIN · FOLLOW YOUR CURIOSITY'}];
function showDiscover(tab='quests'){openSheet('A LITTLE CLOSER TO NATURE',`<h2>There’s a world<br>on your doorstep.</h2><p>You don’t need to go far. You don’t need to know the names. Start by noticing.</p><div class="discovery-tabs"><button class="${tab==='quests'?'active':''}" data-discover-tab="quests">Little quests</button><button class="${tab==='notes'?'active':''}" data-discover-tab="notes">Field notes · ${state.observations.length}</button></div>${tab==='quests'?quests.map(q=>`<article class="mission"><span class="eyebrow">${icon(q.icon)} ${q.time}</span><h3>${q.title}</h3><p>${q.description}</p><div class="mission-meta"><span>No equipment needed</span><span>All experience levels</span></div><button class="primary full" data-quest="${q.id}">Take a closer look ${icon('arrow')}</button></article>`).join(''):`<button class="primary full" data-action="observation" style="margin-bottom:20px">Keep a discovery ${icon('plus')}</button>${state.observations.length?[...state.observations].reverse().map(o=>`<article class="observation"><span class="tag">${esc(o.category)}</span><h3 style="margin-top:12px">${esc(o.title)}</h3>${o.photo?`<img src="${esc(o.photo)}" alt="${esc(o.title)}" loading="lazy">`:''}<p>${esc(o.note)}</p><small>${dateLabel(o.date)}${o.place?' · '+esc(o.place):''}</small><div class="obs-actions"><button data-edit-obs="${esc(o.id)}">Edit</button><button data-delete-obs="${esc(o.id)}">Delete</button></div></article>`).join(''):`<div class="empty">${icon('book')}A small discovery is a lovely place to begin.<br>What did you notice outside today?</div>`}<button class="secondary full" data-action="export-notes" style="margin-top:15px" ${state.observations.length?'':'disabled'}>Download field notes ${icon('download')}</button>`}<p class="fine-print">${tab==='quests'?'Prompts for wherever you are, rather than a live map of nearby places.':'Private notes, saved on this device. Photos and observations have not been submitted to a citizen-science project.'}</p>`,'discover');}
function showQuest(id='tree'){const q=quests.find(q=>q.id===id)||quests[0];openSheet('A LITTLE CURIOSITY',`<div class="success-mark">${icon(q.icon)}</div><span class="eyebrow">${q.time}</span><h2 style="margin-top:16px">${q.title}</h2><p>${q.description}</p><div class="mission" style="margin-top:0"><h3 style="font-size:18px;margin-top:0">Three things to notice</h3><p>${q.id==='tree'?'1. What shape are the leaves?<br>2. Is the bark smooth, rough, or patterned?<br>3. Can you spot any tiny visitors?':q.id==='bird'?'1. Is the call high, low, short, or long?<br>2. Is it near you, or in the distance?<br>3. Can you hear another bird answer?':'1. Look at its colours and patterns.<br>2. Notice where it chooses to grow.<br>3. What else is living nearby?'}</p></div><button class="primary full" data-start-note="${q.id}" style="margin-top:20px">Keep what I notice ${icon('book')}</button><button class="secondary full" data-action="walk" style="margin-top:10px">Take it on a walk</button><p class="fine-print">Observe gently. Leave plants and wildlife as you find them. No species identification is required.</p>`,'quest');}
function showObservation(questId='',existingId=''){const existing=state.observations.find(o=>o.id===existingId),q=quests.find(q=>q.id===questId);openSheet('YOUR FIELD NOTES',`<h2>${existing?'Return to a discovery.':'What caught<br>your eye?'}</h2><p>A name, a photo, a small detail. Keep whatever you noticed.</p><form id="observation-form" data-edit="${existing?esc(existing.id):''}"><label class="field-label" for="obs-title">What did you find?</label><input class="field" id="obs-title" name="title" maxlength="90" required placeholder="An oak on the way home" value="${existing?esc(existing.title):''}"><div class="field-pair"><div><label class="field-label" for="obs-category">A little category</label><select class="field" id="obs-category" name="category">${['Trees','Birds','Plants','Insects','Other wonders'].map(c=>`<option ${(existing?.category||q?.category)===c?'selected':''}>${c}</option>`).join('')}</select></div><div><label class="field-label" for="obs-place">Place · optional</label><input class="field" id="obs-place" name="place" maxlength="100" placeholder="Your local park" value="${existing?esc(existing.place||''):''}"></div></div><label class="field-label" for="obs-note">A detail worth remembering</label><textarea class="field" id="obs-note" name="note" maxlength="5000" placeholder="The leaves were…">${existing?esc(existing.note):''}</textarea><div class="photo-input"><label for="obs-photo">${icon('camera')} ${existing?.photo?'Replace your photo · optional':'Add a photo · optional'}</label><input id="obs-photo" name="photo" type="file" accept="image/jpeg,image/png,image/webp" capture="environment"><div class="fine-print">JPG, PNG, or WebP, up to 1 MB. Saved only on this device.</div></div><div class="action-row"><button class="primary" type="submit">Keep this discovery ${icon('book')}</button></div></form><p class="fine-print">These are your own observations, not verified species records. Nothing is uploaded or shared.</p>`,'observation');}
async function readPhoto(file){if(!file||!file.size)return '';if(file.size>1024*1024)throw new Error('Choose a photo under 1 MB, or save your note without one.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Choose a JPG, PNG, or WebP photo.');return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('This photo couldn’t be read.'));reader.readAsDataURL(file);});}
function showImpact(){const km=state.walks.reduce((s,w)=>s+w.distance,0);openSheet('YOUR PART IN A BIGGER WORLD',`<h2>Small actions.<br>Deeper roots.</h2><p>Your walking and noticing are the beginning. Here’s what you’ve done so far.</p><div class="stat-grid"><div class="stat-tile"><strong>${fmt(totalSteps())}</strong><span>steps logged</span></div><div class="stat-tile"><strong>${state.walks.length}</strong><span>walks brought home</span></div><div class="stat-tile"><strong>${state.observations.length}</strong><span>nature discoveries kept</span></div><div class="stat-tile"><strong>${Math.floor(totalSteps()/3000)+1}</strong><span>digital tree level</span></div></div><div class="progress-block"><h3>${km.toFixed(1)} km of a little more outside.</h3><p>Distance combines tracked walks and estimates from manually logged steps.</p></div><button class="secondary full" data-action="activity">See my walking history ↗</button><section class="impact-note"><span class="tag">THE NEXT CHAPTER</span><h3>From everyday steps to nature impact.</h3><p>The ambition is to connect walks, discoveries, and sponsor-funded rewards to verified nature projects. Those partners and contributions aren’t live yet.</p><p style="margin-top:12px"><strong>No real-world restoration has been funded through this preview.</strong> Your digital tree and seeds represent your activity within Seqesta.</p></section>`,'impact');}
function showMenu(){openSheet('SEQESTA',`<h2>Your little world.<br>Your own way.</h2><p>Walking is the start. Curiosity takes it from there.</p><div class="menu-list">${[['activity','footprints','My walks'],['notes','book','My field notes'],['tree','tree','My digital tree'],['settings','settings','Make it mine'],['legacy-notes','heart','My reflection notebook'],['breathe','sun','A quiet moment outside']].map(([a,i,t])=>`<button data-action="${a}">${icon(i)}<span>${t}</span><span>↗</span></button>`).join('')}</div><div class="impact-note"><h3>A companion for everyday nature.</h3><p>Walk, notice, and bring a little of the outside back to your world.</p></div><p class="fine-print" style="margin-top:auto;padding-top:28px">Your progress is stored on this device. This preview has no health-data connection, payouts, or verified impact partners.</p>`,'menu');}
function showSettings(){openSheet('MAKE IT MINE',`<h2>A world that<br>feels like you.</h2><form id="settings-form"><label class="field-label" for="my-name">Your name</label><input class="field" id="my-name" name="name" maxlength="30" placeholder="What should we call you?" value="${esc(state.name)}"><label class="field-label" for="lumi-name">Your companion’s name</label><input class="field" id="lumi-name" name="companion" maxlength="24" required value="${esc(state.companion)}"><button class="primary full" style="margin-top:19px" type="submit">Save names</button></form><label class="field-label">A different light</label><div class="light-options">${[['day','Daylight'],['blue','Blue sky'],['dusk','Golden hour']].map(([id,label])=>`<button data-light="${id}" class="${state.light===id?'active':''}" aria-pressed="${state.light===id}">${label}</button>`).join('')}</div><div class="settings-row"><span><b>Less motion</b><small>Stillness for your companion and world.</small></span><button class="toggle" data-action="toggle-motion" role="switch" aria-checked="${state.reduced}" aria-label="Less motion"><span></span></button></div><p class="fine-print">Drag with one finger to rotate. Pinch with two to zoom. On a computer, drag and use the scroll wheel, or use the globe buttons.</p>`,'settings');}
function showCompanion(){openSheet('YOUR NATURE COMPANION',`<h2>Hello, I’m ${esc(state.companion)}.</h2><p>A little keeper of your world. I’ll help you find a reason to step outside.</p><span class="tag">GUIDED PREVIEW · SAMPLE REPLIES</span><div class="suggestion-list"><button data-chat="What can I notice on a short walk?">A little walk idea</button><button data-chat="How does my tree grow?">My growing tree</button><button data-chat="How do I earn seeds?">How seeds work</button></div><div class="chat-log" id="chat-log"></div><form class="chat-form" id="chat-form"><input name="message" maxlength="1000" required placeholder="Ask ${esc(state.companion)}…" aria-label="Message companion"><button type="submit" aria-label="Send message">${icon('arrow')}</button></form><p class="fine-print">Sample guidance, not a connected AI or a species identification service. Conversation lasts for this visit.</p>`,'companion');renderChat();}
function renderChat(){const target=$('#chat-log');if(!target)return;target.innerHTML=chats.map(m=>`<div class="chat-bubble ${m.role==='user'?'user':''}">${esc(m.text)}</div>`).join('');target.scrollTop=target.scrollHeight;}
function sendChat(text){const t=text.trim();if(!t)return;chats.push({role:'user',text:t});let reply;const lower=t.toLowerCase();if(/tree|grow|level/.test(lower))reply='Your digital tree grows one level for every 3,000 steps you log. Try a short walk, bring it home, and tap your tree to see how it’s growing.';else if(/seed|reward|earn/.test(lower))reply='Every 100 steps earns one virtual seed. Save 15 for daisies, 30 for a wildflower patch, or 50 for a pocket of woodland. You can find them in Rewards.';else if(/identify|species|what bird|what plant/.test(lower))reply='I can’t identify species in this preview. You can keep a photo and the details you notice in your field notes, without needing to know its name.';else if(/impact|sponsor|money|planting/.test(lower))reply='Your world reflects your walking and discoveries. Real restoration partners and sponsor-funded contributions aren’t connected yet, so no real-world planting or funding is being counted.';else reply='On your next walk, choose one tree you usually pass. Notice its leaf shape, its bark, and any tiny visitors. A few minutes of curiosity is plenty. You can keep what you notice in Discover.';chats.push({role:'assistant',text:reply});if(sheetName!=='companion')showCompanion();else renderChat();$('#chat-form')?.reset();}
function showBreathe(){openSheet('A QUIET MOMENT OUTSIDE',`<h2 class="center">Let the world<br>set a slower pace.</h2><p class="center">Pause somewhere comfortable. Notice the air, the sounds, and the ground beneath you.</p><div class="breathing-circle" id="breathing-circle"><span id="breathing-label">Settle in</span></div><div class="breathing-count" id="breathing-count">In for 4. Out for 6. Six easy breaths.</div><button class="primary full" data-action="start-breath" id="breathing-start">Begin a quiet minute</button><p class="fine-print center">Breathe comfortably. Stop whenever you like.</p>`,'breathe');}
function startBreathing(){if(breathTimer){clearInterval(breathTimer);breathTimer=null;$('#breathing-label').textContent='A little pause';$('#breathing-start').textContent='Begin again';$('#breathing-circle').classList.remove('expand');return;}const start=Date.now();$('#breathing-start').textContent='End this moment';function tick(){const s=Math.floor((Date.now()-start)/1000);if(!$('#breathing-label')){clearInterval(breathTimer);breathTimer=null;return;}if(s>=60){clearInterval(breathTimer);breathTimer=null;$('#breathing-label').textContent='Welcome back';$('#breathing-count').textContent='A minute, just for you.';$('#breathing-start').textContent='Breathe again';$('#breathing-circle').classList.remove('expand');return;}const part=s%10;$('#breathing-label').textContent=part<4?'Breathe in':'Breathe out';$('#breathing-circle').classList.toggle('expand',part<4);$('#breathing-count').textContent=`Breath ${Math.floor(s/10)+1} of 6 · ${part<4?4-part:10-part}`;}tick();breathTimer=setInterval(tick,250);}
function showLegacyNotes(){let entries=[];try{entries=JSON.parse(localStorage.getItem('seqesta-v1')||'{}').entries||[];}catch{}openSheet('YOUR REFLECTION NOTEBOOK',`<h2>Little things,<br>still kept.</h2><p>Your thoughts from the earlier Seqesta experience are here.</p>${entries.length?[...entries].reverse().map(e=>`<article class="observation"><h3>${esc(e.title)}</h3><p>${esc(e.body)}</p><small>${dateLabel(e.date)}</small></article>`).join(''):'<div class="empty">No earlier reflections saved on this device.</div>'}<button class="primary full" data-action="new-reflection" style="margin-top:20px">Write a thought ${icon('plus')}</button>`,'legacy');}
function newReflection(){openSheet('A THOUGHT TO KEEP',`<h2>What stayed<br>with you today?</h2><form id="reflection-form"><label class="field-label" for="reflection-title">Give it a name</label><input class="field" id="reflection-title" name="title" maxlength="100" placeholder="A little moment"><label class="field-label" for="reflection-body">Your thought</label><textarea class="field" id="reflection-body" name="body" maxlength="12000" required></textarea><button class="primary full" type="submit" style="margin-top:20px">Keep this thought</button></form>`,'reflection');}
function exportNotes(){const content=state.observations.map(({photo,...rest})=>({...rest,hasPhoto:!!photo}));const blob=new Blob([JSON.stringify({app:'Seqesta',exported:new Date().toISOString(),observations:content},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='seqesta-field-notes.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Field notes downloaded. Photos remain on this device.');}
Object.assign(actions,{
 menu:showMenu,'start-gps':startWalk,'pause-walk':pauseWalk,'finish-walk':finishWalk,
 'resume-walk':()=>{if(walk?.paused)pauseWalk();closeSheet();},
 'discard-walk':()=>openSheet('LEAVE THIS WALK BEHIND?',`<h2>Discard this walk?</h2><p>Your time and distance from this walk won’t be saved. Your previous walks will stay.</p><div class="action-row"><button class="secondary" data-action="finish-walk">Keep it</button><button class="primary" data-action="confirm-discard">Discard walk</button></div>`,'discard'),
 'confirm-discard':()=>{clearWalk();closeSheet();toast('This walk was discarded.');},
 rewards:showRewards,discover:()=>showDiscover(),notes:()=>showDiscover('notes'),quest:()=>showQuest(),observation:()=>showObservation(),impact:showImpact,settings:showSettings,
 'toggle-motion':()=>{state.reduced=!state.reduced;persist();refresh();showSettings();},
 companion:showCompanion,breathe:showBreathe,'start-breath':startBreathing,'legacy-notes':showLegacyNotes,'new-reflection':newReflection,'export-notes':exportNotes
});
document.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;
 if(b.dataset.buy)buyReward(b.dataset.buy);
 if(b.dataset.discoverTab)showDiscover(b.dataset.discoverTab);
 if(b.dataset.quest)showQuest(b.dataset.quest);
 if(b.dataset.startNote)showObservation(b.dataset.startNote);
 if(b.dataset.editObs)showObservation('',b.dataset.editObs);
 if(b.dataset.deleteObs){const id=b.dataset.deleteObs;openSheet('YOUR FIELD NOTES',`<h2>Let this discovery go?</h2><p>This field note and its photo will be removed from this device.</p><div class="action-row"><button class="secondary" data-action="notes">Keep it</button><button class="primary" data-confirm-delete="${esc(id)}">Delete note</button></div>`,'delete');}
 if(b.dataset.confirmDelete){state.observations=state.observations.filter(o=>o.id!==b.dataset.confirmDelete);persist();showDiscover('notes');toast('Field note deleted.');}
 if(b.dataset.light){state.light=b.dataset.light;persist();refresh();showSettings();}
 if(b.dataset.chat)sendChat(b.dataset.chat);
});
document.addEventListener('submit',async e=>{
 const form=e.target;if(!['finish-walk-form','observation-form','settings-form','chat-form','reflection-form'].includes(form.id))return;e.preventDefault();const f=new FormData(form);
 if(form.id==='finish-walk-form'){
  if(!walk)return;const steps=Number(f.get('steps')),estimated=Math.round(sessionDistance/.00075),source=sessionDistance>.001&&steps===estimated?'gps':'manual';
  try{const entry=saveWalk({steps,minutes:Math.max(1,elapsedMs()/60000),title:String(f.get('title')).trim(),source,distance:source==='gps'?sessionDistance:undefined});clearWalk();showWalkSuccess(entry);}catch(err){toast(err.message);}
 }else if(form.id==='observation-form'){
  const submit=form.querySelector('[type="submit"]');submit.disabled=true;
  try{const existing=state.observations.find(o=>o.id===form.dataset.edit);const photo=await readPhoto(f.get('photo'))||existing?.photo||'';const title=String(f.get('title')).trim();if(!title)throw new Error('Add a name for your discovery.');const note={id:existing?.id||crypto.randomUUID(),title,note:String(f.get('note')).trim(),category:String(f.get('category')),place:String(f.get('place')).trim(),date:existing?.date||new Date().toISOString(),photo};const previous=[...state.observations];if(existing)state.observations=state.observations.map(o=>o.id===existing.id?note:o);else state.observations.push(note);if(!persist()){state.observations=previous;submit.disabled=false;return;}showDiscover('notes');toast('A small discovery, kept.');}catch(err){toast(err.message);submit.disabled=false;}
 }else if(form.id==='settings-form'){state.name=String(f.get('name')).trim();state.companion=String(f.get('companion')).trim()||'Lumi';persist();refresh();toast('Your world feels a little more like you.');}
 else if(form.id==='chat-form')sendChat(String(f.get('message')));
 else if(form.id==='reflection-form'){try{const old=JSON.parse(localStorage.getItem('seqesta-v1')||'{}');old.entries=old.entries||[];const body=String(f.get('body')).trim();if(!body){toast('Write a thought before saving.');return;}old.entries.push({id:crypto.randomUUID(),date:new Date().toISOString(),title:String(f.get('title')).trim()||'A little moment',body,kind:'A THOUGHT'});localStorage.setItem('seqesta-v1',JSON.stringify(old));showLegacyNotes();toast('Your thought is kept.');}catch{toast('This thought couldn’t be saved on your device.');}}
});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&walk&&!walk.paused){pauseWalk();walk.message='Your walk paused while Seqesta was away. Resume to keep tracking.';}});
window.addEventListener('beforeunload',e=>{if(walk){e.preventDefault();e.returnValue='';}});

if(document.modelContext?.registerTool){
 const controller=new AbortController();
 const tools=[{name:'log_walk',description:'Log a self-reported walk, earn virtual seeds, and show the walk summary. Saves to this device.',inputSchema:{type:'object',properties:{steps:{type:'integer',minimum:1,maximum:100000},minutes:{type:'number',minimum:1,maximum:1440},title:{type:'string',maxLength:70}},required:['steps','minutes'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||!Number.isInteger(input.steps)||typeof input.minutes!=='number'||input.minutes<1||input.minutes>1440||input.title!==undefined&&(typeof input.title!=='string'||input.title.length>70))throw new Error('Supply valid steps, minutes, and an optional title.');const entry=saveWalk({...input,source:'manual'});showWalkSuccess(entry);return {walkId:entry.id,seedsEarned:entry.seeds,balance:balance(),storage:'this device'};}},{name:'get_nature_progress',description:'Read walking totals, virtual seed balance, and the number of private field notes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){return {steps:totalSteps(),walks:state.walks.length,seeds:balance(),discoveries:state.observations.length,realWorldContributions:0};}}];
 for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}}
 window.addEventListener('pagehide',()=>controller.abort(),{once:true});
}
